
Commands:
  NoPermission: "&cYou do not have permission to run this"

Inventory:
  BossEggs:
    Title: "&cBoss Eggs"
    BackgroundItem: BLACK_STAINED_GLASS_PANE
    
Bosses:
  Piglin:
    Entity:
      Name: "&cPiglin Boss"
      # ArmorTypes: "IRON", "GOLD", "DIAMOND", "NETHERITE", "NONE"
      ArmorType: "DIAMOND"
      ProtectionLevel: 20
      ArmorUnbreakable: true
      ItemType: "DIAMOND_SWORD"
      #ItemEnchants example: "<ENCHANTMENT> <LEVEL>"
      ItemEnchants:
      - "DAMAGE_ALL 10"
      - "FIRE_ASPECT 2"
      Health: 150
    Egg:
      Material: "PIGLIN_SPAWN_EGG"
      Name: "&cPiglin Boss"
      Glowing: false
      Lore:
      - '&7Summon this boss in pvp'
    Pvp:
      # {HEALTH} - Boss' health remaining
      # {MAXHEALTH} - Boss' max health
      HitMessage: "HP Left: {HEALTH}"
      # Format - "<ITEM> <AMOUNT>"
      Drops:
      - "DIAMOND 64"
      - "EMERALD 128"
      #Commands that are ran when boss dies
      Commands:
      - "bc &bBoss Defeated"
      ExperienceDrop: 1000
      #Commands that are ran when the boss dies for the player who killed the boss
      # {PLAYER} - Player who killed the boss
      FinalHitCommands:
      - "give {PLAYER} DIAMOND 64"
      - "bc {PLAYER} got the last hit on the boss and won 64 diamonds"
    